# This Name will be visible on github action tab [Pipeline Name]
name: CICD

# Trigger Condition - Manually with option pass env to deploy
on:                
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

# Trigger Condition - when merged to main and any updates detected in .md files

# on:       
#   push:
#     branches: [main]
#     paths: 
#      - "**.md"

# Trigger Condition - when pull Request created

# on:       
#   pull_request:
#     branches: [main]
#     paths: 
#      - "**.md"

# Variables Defination
env:
  myvar: "Variable value"  # can be reffered as $myvar in steps

jobs: # Jobs Defination.

  code-checkout: # Job 1
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        run: echo "Copying the code from repo to pipeline"
        
  build:  # Job 2
    needs: [code-checkout]   # This is Depends on block can take multiple arguments
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the code using docker/ any technology"
        
  test:  # Job 3
    needs: [build]       
    runs-on: ubuntu-latest
    steps:
      - name: Code Tests
        run: echo "Testing to be done before deploying the code"
        
  deploy: # Job 4
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "Deploy the code to Servers"
  
  
