name: Github Runner

on:
    workflow_dispatch:

jobs:
    ubuntu:
      runs-on: ubuntu-latest
      steps:
        - name: ubuntu version
          run:  cat /etc/os-release

        - name: packages version
          run: |
            echo "Docker Version"
            docker --version
            echo "python Version"
            python --version
            echo "Node Version"
            node --version
            echo "Git Version"
            git --version

    windows:
      runs-on: windows-latest
      steps:
        - name: windows version
          run: |
            Write-Host "=== GitHub Runner OS Variables ==="
            Write-Host "Runner OS: ${{ runner.os }}"
            Write-Host "Runner Image: $env:ImageVersion"
            
            Write-Host "=== System OS Details ==="
            [System.Environment]::OSVersion.Version
            Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version, BuildNumber
            
            Write-Host "=== System Host Name ==="
            hostname
            $env:COMPUTERNAME
    macos:
      runs-on: macos-latest
      steps:
        - name: macos-version
          run: |
            echo "=== GitHub Runner OS Variables ==="
            echo "Runner OS: ${{ runner.os }}"
            echo "Runner Image: $ImageVersion"
            
            echo "=== System OS Details ==="
            sw_vers
            
            echo "=== System Host Name ==="
            hostname
            scutil --get LocalHostName