name: matrix

on:
    workflow_dispatch:

jobs:
    version-validation:
        strategy:
          fail-fast: false # false means all the test will be executed even if something is failed in between.
          
          matrix:
            py-version: ["3.11", "3.12", "3.13"]
            os-version: ["ubuntu-22.04", "ubuntu-slim" ]
            exclude: # Below combination will be ignored in matrix
                - os-version: ubuntu-22.04
                  py-version: "3.11"

        runs-on: ${{ matrix.os-version }}
        steps:
          - name: checkout code
            uses: actions/checkout@v4 

          - uses: actions/setup-python@v6
            with:
                python-version: ${{ matrix.py-version }} 

          - name: Shell Script
            run: sudo chmod u+x matrix.sh && ./matrix.sh ${{ matrix.py-version }} ${{ matrix.os-version }}

