name: matrix

on:
    workflow_dispatch:

jobs:
    version-validation:
        strategy:
          fail-fast: false # false means all the test will be executed even if something is failed in between.
          matrix:
            py-version: ["3.11", "3.12", "3.13"]

        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4 

          - uses: actions/setup-python@v6
            with:
                python-version: ${{ matrix.py-version }} 
<<<<<<< HEAD

          - name: Shell Script
            run: sudo chmod u+x matrix.sh && ./matrix.sh ${{ matrix.py-version }}
=======
          - name: Shell Script
            run: ./matrix.sh ${{ matrix.py-version }}
>>>>>>> e1afb775b793cf83d89b9335115905aa52006a69

