name: Multi-Jobs

on:
    workflow_dispatch:

# Defining Environment variable at work flow level available in all the jobs
env:
    APP_NAME: myapp

jobs:

    build:

      # Defining Environment variable at job level available in all the steps present that job        
      env:    
        ENVIRONMENT: staging

      runs-on: ubuntu-latest
      outputs:
        date: ${{ steps.date.outputs.today }}
        name: ${{ steps.date.outputs.name }}

      steps:
        - name: Build App 
          run: echo "Building the App"
        - name: Environment Variable

          # Defining Environment variable at Steps level available in all the steps present that job
          env:
            VERSION: 1.0.0
          run: |
            echo "All Level of Environment variables"
            echo "worflow level variable - $APP_NAME"
            echo "job level variable - $ENVIRONMENT"
            echo "step level variable - $VERSION"

        - name: date today
          id: date
          run: |
           echo "today=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
           echo "name=Devendra" >> $GITHUB_OUTPUT

    test:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - name: Test App
          run: echo "Testing the App"
        - name: Environment Variable
          run: |
            echo "All Level of Environment variables"
            echo "worflow level variable - $APP_NAME"
            echo "job level variable - $ENVIRONMENT"
            echo "step level variable - $VERSION" 

    deploy:
      needs: [test]
      runs-on: ubuntu-latest
      steps:
        - name: Deploy App
          run: echo "Deploying the App"
        - name: Environment Variable
          run: |
            echo "All Level of Environment variables"
            echo "worflow level variable - $APP_NAME"
            echo "job level variable - $ENVIRONMENT"
            echo "step level variable - $VERSION"

    output:
        runs-on: ubuntu-latest
        needs: [build, deploy]
        steps:
          - name: Date and name
            run: echo "Hi ${{ needs.build.outputs.name }} today date is ${{ needs.build.outputs.date }}" 