name: Trigger_X_Matrix

on:
    pull_request:
        branches: [main]

#  Cron job
    # schedule:
    #   - cron: '0 0 * * *'

jobs:
  PR_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Task-1
        run: echo "Automatically triggers when PR is Created"

# Add a comment to create a PR Trigger Test