name: Secret-Read

on:
    workflow_dispatch:

jobs:
    read_secret:
        runs-on: ubuntu-latest
        steps:
          - name: check Secret set
            env:
               mysecret: ${{ secrets.MY_SECRET_MESSAGE }}"
            run: |
              if [[ -n $mysecret ]]; then
                echo "The secret is set - true"
              else
                echo "The secret is set - true"
              fi
          - name: Create Artifact
            run: |
              echo "Hello world form pipeline" >> hello.txt
          - uses: actions/upload-artifact@v7
            with:
              name: my-artifact
              # path of file/ folder which we want to create artifact of. 
              path: hello.txt

          - name: Path for Artificat Download
            run: sudo mkdir -p /home/ubuntu/App

          - uses: actions/download-artifact@v8
            with:
              name: my-artifact
              path: /home/ubuntu/App

          - name: Display structure of downloaded files
            run: ls -R /home/ubuntu/App

          - name: Checkout code
            uses: actions/checkout@v4

          - name: Download python Package
            uses: actions/setup-python@v6
            with:
              python-version: '3.13' 

          - name: Install Requirements
            run: pip install -r requirements.txt 

          - name: Run python file
            run: python app.py
          
