name: Secret-Read

on:
    workflow_dispatch:

jobs:
    read_secret:
        runs-on: ubuntu-latest
        steps:
          - name: check Secret set
            env:
               mysecret: ${{ secrets.MY_SECRET_MESSAGE }}"
            run: |
              if [[ -n $mysecret ]]; then
                echo "The secret is set - true"
              else
                echo "The secret is set - true"
              fi
          - name: Create Artifact
            run: |
              echo "Hello world form pipeline" > hello.txt
          - uses: actions/upload-artifact@v7
            with:
              name: my-artifact
              path: hello.txt
