name: Reusable Build

on:
    workflow_call:
        inputs:
          app_name:
            required: true
            type: string
          environment:
            required: true
            type: string
            default: staging
        secrets:
          docker_token:
            required: true
        
        # Outputs is used to send the output back to the parent and can be shared with other jobs aswell
        outputs:
          build_version: 
            value: ${{ jobs.Build.outputs.build_ver }}
jobs:
    Build:
      outputs:
        build_ver: ${{ steps.version.outputs.build_version }}

      runs-on: ubuntu-latest
      steps: 
        - name: checkout code
          uses: actions/checkout@v6

        - name: Build App
          run: echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}" 

        - name: Generate Build Version
          id: version
          run: |
            SHORT_SHA=$(git rev-parse --short HEAD)
            BUILD_VERSION="v1.0-${SHORT_SHA}"
            echo "build_version=${BUILD_VERSION}" >> $GITHUB_OUTPUT
            echo "Generated version: ${BUILD_VERSION}"

    Secret_check:
      runs-on: ubuntu-latest
      steps:
        - name: Check Secret
          run: |
            if [[ -n ${{ secrets.docker_token }} ]]; then
              echo "Secret is present"
            else
              echo "Secret is NOT present"
            fi  