name: Self-Hosted Runner

on:
    workflow_dispatch:

jobs:
    Startup:
        runs-on: [Devendra]  # Label present on self hosted agent
        steps:
          - name: Runner Configs
            run: |
              echo "===Hostname==="
              hostname
              echo "===Current Working Directory==="
              pwd
              echo "Folder Created at /home/ubuntu/Devendra"
              mkdir -p /home/ubuntu/Devendra

            