name: Self-Hosted Runner

on:
    workflow_dispatch:

jobs:
    Startup:
        runs-on: [self-hosted, Dev]
        steps:
          - name: Runner Configs
            run: |
              echo "===Hostname==="
              hostname
              echo "===Current Working Directory==="
              pwd
              echo "Folder Created at /home/ubuntu/DevOps"
              mkdir -p /home/ubuntu/DevOps

