name: Self-Hosted Runner

on:
    workflow_dispatch:

jobs:
    Startup:
        runs-on: [self-hosted, Dev]
        steps:
          - name: Runner Configs
            run: |
              hostname
              uname
