name: Smart Trigger - Paths Filter

on:
  push:
    branches:
      - main

    paths:
      - 'src/**'
      - 'app/**'

# we can use only 1 at a time, means both cannot be used at same time on single yml file 
    # paths-ignore:
    #   - 'src/docs/**'
    #   - 'app/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Trigger Information
        run: |
          echo "Workflow triggered!"
          echo "Branch : ${{ github.ref_name }}"
          echo "Commit : ${{ github.sha }}"